package com.isti.traceview;

// Special exception generated by Traceview lib
public class UndoException extends Exception {

	private static final long serialVersionUID = 1L;

	public UndoException() {
		super();
	}

	public UndoException(String str) {
		super(str);
	}
}
