language: java
os:
  - linux
jdk:
  - openjdk8
#  - openjdk11

git:
  submodules: false

before_install:
  - sed -i 's/git@code.usgs.gov:/https:\/\/code.usgs.gov\//' .gitmodules
  - git submodule update --init --recursive

sudo: false
script: gradle check
