package edu.sc.seis.seisFile.segd;

// Special exception generated by segd lib
public class SegdException extends Exception {
	private static final long serialVersionUID = 1L;

	public SegdException() {
		super();
	}

	public SegdException(String str) {
		super(str);
	}
}
