package com.isti.traceview.data;

// Special exception generated by traceview.data lib
public class PlotDataException extends Exception {
	
	private static final long serialVersionUID = 1L;

	public PlotDataException() {
    		super();
	}

	public PlotDataException(String str) {
		super(str);
	}

	public PlotDataException(String str, Exception e) {
		super(str, e);
	}
}
