package com.isti.traceview;

/**
 * Special exception generated by TraceView library
 * @author Max Kokoulin
 */

public class TraceViewException extends Exception {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public TraceViewException(){
		super();
	}
	
	public TraceViewException(String str){
		super(str);
	}
}
